bash src/testing_scripts/microbenchmark/memtis_commands/hottest_27G_read.sh
bash src/testing_scripts/microbenchmark/memtis_commands/hottest_27G_write.sh

bash src/testing_scripts/microbenchmark/memtis_commands/hottest_13.5G_read.sh
bash src/testing_scripts/microbenchmark/memtis_commands/hottest_13.5G_write.sh

bash src/testing_scripts/microbenchmark/memtis_commands/hottest_10G_read.sh
bash src/testing_scripts/microbenchmark/memtis_commands/hottest_10G_write.sh
